# Workflow per costruire e pubblicare un sito Jekyll su GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Eseguito su push al branch principale
  push:
    branches:
      - "main"

  # Possibilità di eseguire manualmente dal tab Actions
  workflow_dispatch:

# Permessi necessari per GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Gestione delle esecuzioni concorrenti
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v4
